name: nomad_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.4
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+2
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  google_sign_in: ^6.1.2
  font_awesome_flutter: ^10.4.0
#  firebase_auth_project: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
